language: python

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.8.0
    - APP_NAME=sample_travis_ci
    - DOCKER_HUB_ACCOUNT=va034600
    # ECR
    - PATH=$HOME/.local/bin:$PATH
    - AWS_DEFAULT_REGION=ap-northeast-1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  - # ECR
  - pip install -U pip
  - pip install awscli

script:
  - echo "script"

after_success:
  - docker --version
  - docker build -t $APP_NAME:latest -f docker/Dockerfile .
  - docker images

  # Docker Hub public
  - docker tag $APP_NAME:latest $DOCKER_HUB_ACCOUNT/${APP_NAME}_pub:${TRAVIS_TAG}
  - docker push $DOCKER_HUB_ACCOUNT/${APP_NAME}_pub:${TRAVIS_TAG}

  # Docker Hub private
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ACCOUNT" --password-stdin
  - docker tag $APP_NAME:latest $DOCKER_HUB_ACCOUNT/$APP_NAME:${TRAVIS_TAG}
  - docker push $DOCKER_HUB_ACCOUNT/$APP_NAME:${TRAVIS_TAG}

  # ECR
  - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  - docker tag $APP_NAME:latest $AWS_ECR_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:${TRAVIS_TAG}
  - docker push $AWS_ECR_ACCOUNT.dkr.ecr.ap-northeast-1.amazonaws.com/$APP_NAME:${TRAVIS_TAG}

branches:
  only:
#  - master
  - develop
  - "/^v?[0-9\\.]+/"