version: '3'
services:
  api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: va034600/sample_travis_ci:1

    working_dir: /usr/src/app/travis_ci
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"